#!/bin/sh
set -eu

TOKEN_FILE="${SYMPHONY_GITHUB_TOKEN_FILE:?missing SYMPHONY_GITHUB_TOKEN_FILE}"

case "${1:-}" in
  *Username*)
    printf '%s\n' x-access-token
    ;;
  *Password*)
    cat "$TOKEN_FILE"
    ;;
  *)
    exit 1
    ;;
esac
